### ISSUE TITLE
Please add the implementation docs

### ISSUE THREAD

**Issue by fathah** [raycardillo/dart_phonetics#4]
Hi there, 
The dependency is pretty awesome. Please provide the implementation methods.

**Comment by raycardillo** [comment]
Hello, I'm in the middle of a relocation, sorry for the delay. I will be spending some time on this project when things settle down a bit. However, can you be more specific about exactly what you're asking for here? Provide an example if possible, and I'll take a look.

**Comment by raycardillo** [comment]
Closing this issue because no information provided. The documentation has been available in source code an generated documentation since release `0.2.0`.

https://pub.dev/documentation/dart_phonetics/latest/
